name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Files list
        run: ls

      - name: View key.pem contents
        run: cat nnew.pem


      #      - name: Install dependencies
#        run: |
#          sudo apt-get update -y
#          sudo apt-get install -y default-jdk maven git
#          git clone https://github.com/daniyaradil04/aws_demo
#          cd aws_demo/site
#          mvn clean install

#      - name: SSH Remote Commands
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: 3.79.113.22
#          username: ubuntu
#          port: 22
#          script: whoami

      - name: Deploy application
        run:  chmod 400 nnew.pem; ssh -i nnew.pem ubuntu@3.79.113.22; yes;
              "cd /home/ubuntu/aws_demo/; git pull origin main; mvn clean install; nohup mvn spring-boot:run -e -Dsolr.solr.home=./solr &"
